name = "defendml-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "AUTH_USERS"
id = "1e2281288d1340848dd38cf19e45a004"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "a3c27a772f0746e183be83a924a4d94b"

[[kv_namespaces]]
binding = "AUDIT_LOG"
id = "e30011d67c0a47c395da47751419cd58"

# Environment Variables (set these in Cloudflare Dashboard)
# SUPABASE_URL = "https://your-project.supabase.co"
# SUPABASE_SERVICE_ROLE = "your-service-role-key"
# JWT_SECRET = "your-jwt-secret"
# ANTHROPIC_API_KEY = "sk-ant-..."
# CORS_ORIGIN = "https://defendml.com,https://app.defendml.com"
# MOCK_MODE = "false"
# STRICT_MODE = "false"
